[package]
name = "circles"
version = "0.1.0"
authors = ["Emily Herbert <herbert.e@northeastern.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
